name: dart_mappable_extras
description: Untagged Unions and Undefined Types for dart_mappable
version: 0.2.2
repository: https://github.com/dickermoshe/dart_mappable_extras

environment:
  sdk: ^3.8.0

dependencies:
  dart_mappable: ^4.0.0

dev_dependencies:
  build_runner: ^2.0.0
  dart_mappable_builder: ^4.0.0
  lints: ^5.0.0
  test: ^1.24.0
